### ISSUE TITLE
iOS SDK 更新

### ISSUE THREAD

**Issue by gengen1988** [ETENG-OSP/xgpush-cordova#14]
更新到了 2.4.5。分支是 ios-2.4.5，请大家测下，没问题我就合并了

这次腾讯提供了一个 xcode 6.4 的兼容包，不知道是做什么用的。也许和 armv7s 有关系？

**Comment by JrontEnd** [comment]
好的，我测试下

**Comment by JrontEnd** [comment]
@gengen1988 经过测试，升级SDK后，打包成功仍须去掉armv7s；
iOS的全推和别名能正常使用；
android还未测试。

**Comment by gengen1988** [comment]
ok，谢谢，我这就合并到 master

android 部分没变化不用测
