### ISSUE TITLE
textmessage 没反应

### ISSUE THREAD

**Issue by sz520mm** [ETENG-OSP/xgpush-cordova#16]
试用了很多推送插件，这个是最好用的了，通知栏消息正常，但在ionic的.ready中添加以下事件没反应。请问需要如何处理。谢谢！

xgpush.on('textmessage', function(e) {
  // 事件处理方法
  alert(JSON.stringify(arguments, null, 2));
});

**Comment by gengen1988** [comment]
收到，你先按下面的步骤试试：

1. 检查下发送的是推送通知还是消息命令。textmessage 是用于接受接收信鸽的消息命令的，发送的推送通知在这里拿不到；
2. 检查下日志，看看有没有异常；
3. 看不出来的话，报下版本，包括：cordova 版本号、cordova platform 版本号、ionic 版本号

**Comment by sz520mm** [comment]
发送消息命令可以了，但我希望达到的目的是推送一条信息，用户在点击该信息后进入应用，同时触发程序逻辑。发送一个带有自定义 URL scheme 的通知 能提供个示例吗？谢谢！

**Comment by gengen1988** [comment]
可以发推送通知时，设定当用户点击通知时打开一个 URL，比如：myfancyapp://?param1=a&param2=b

然后用插件，监听 myfancyapp 的打开事件：https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by sunlu** [comment]
看API，可以增加NotifactionClicked事件解决此类问题，不需要用URL方式。

**Comment by gengen1988** [comment]
这个是可以，但不一定保证这个事件触发时，webview 还活着，这样在 hybrid app 里不好处理。用 url 的方式一定能打开 app
