### ISSUE TITLE
如何获取打开通知的参数

### ISSUE THREAD

**Issue by jovi-Li** [ETENG-OSP/xgpush-cordova#23]
安卓下测试接收通知和消息命令都能成功 
请教下 如何点击获取通知传递的参数 
按照文档提示 我添加了插件customer url scheme  本地测试直接通过url打开是能接收到url参数的，但是信鸽 创建通知只能选择打开应用 或者打开应用制定页 ，打开url参数验证失败，
请问怎么获取通知里面的参数？？

**Comment by gengen1988** [comment]
不要用信鸽的网页来发送通知。那个不支持除了 http 和 https 以外的 url

**Comment by gengen1988** [comment]
用 RESTFul API 或 服务端 SDK

**Comment by jovi-Li** [comment]
谢谢

**Comment by jovi-Li** [comment]
测试可以 ，但是 体验一点也不好 ，会弹出提示框
而且 ，测试发现重新打开一个新的app网页 调试 就是两个网站了 很麻烦。。
能不能增加通知打开的回调函数 ？

**Comment by gengen1988** [comment]
1. 弹提升框提示什么?
2. 两个 activity 的问题用 singleinstance 来解决
